target_controller:
  ros__parameters:
    rate: 10.0 # control loop frequency [Hz]
    parent_frame: world # Parent Reference frame (world)
    child_frame: vehicle # Child Reference frame (vehicle)
    lower_velocity_threshold: 1.34 # the lower threshold of the velocity that cooresponds to lookahead_min
    upper_velocity_threshold: 5.36 # the above, but for max/upper
